# Generated by Django 3.0.6 on 2020-05-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200505_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='end_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='start_time',
            field=models.CharField(max_length=50),
        ),
    ]
